_wandb:
    value:
        cli_version: 0.23.0
        e:
            uifitqvih6gecdak89pdlabs0yb7c31z:
                args:
                    - debug=false
                    - logging.run_name=Bi_RankNet_Random_neg_SameLR
                    - model.type=bi_encoder
                    - model.head_type=ranknet
                    - data.train_file=data/processed/training_dataset_abstract_cleaned_v3.csv
                    - training.epochs=3
                    - training.batch_size=32
                    - training.learning_rate=2e-5
                    - training.head_learning_rate=2e-5
                codePath: scripts/run_train.py
                codePathLocal: scripts/run_train.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "982820896768"
                        used: "805930532864"
                email: reoreo01.123@gmail.com
                executable: /usr/bin/python
                git:
                    commit: 2337d345b1e010b6cfbabbee6300d940ca645a17
                    remote: https://github.com/ku6kaw/S2ORCRanker
                gpu: NVIDIA RTX A6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-b6e6e0e3-0979-08d4-7b26-7ebfb7c03ea4
                host: lssgpu
                memory:
                    total: "67242205184"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/kurokawa/Projects/S2ORCRanker/scripts/run_train.py
                python: CPython 3.10.12
                root: /home/kurokawa/Projects/S2ORCRanker
                startedAt: "2025-11-25T01:10:40.392750Z"
                writerId: uifitqvih6gecdak89pdlabs0yb7c31z
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 51
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 51
                - 53
                - 71
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.12
            "5": 0.23.0
            "6": 4.40.0
            "12": 0.23.0
            "13": linux-x86_64
data:
    value:
        format: pair
        num_proc: 4
        train_file: data/processed/training_dataset_abstract_cleaned_v3.csv
        val_size: 0.2
debug:
    value: false
logging:
    value:
        project_name: s2orc-ranker
        run_name: Bi_RankNet_Random_neg_SameLR
        tags: []
        use_wandb: true
model:
    value:
        head_type: ranknet
        max_length: 512
        name: allenai/scibert_scivocab_uncased
        type: bi_encoder
seed:
    value: 42
training:
    value:
        batch_size: 32
        epochs: 3
        eval_steps: 50
        head_learning_rate: 2e-05
        learning_rate: 2e-05
        logging_steps: 10
        margin: 1
        output_dir: /home/kurokawa/Projects/S2ORCRanker/models/checkpoints/bi_encoder/Bi_RankNet_Random_neg_SameLR
        patience: 3
        save_steps: 50
        save_total_limit: 2
        warmup_ratio: 0.1
        weight_decay: 0.01
