_wandb:
    value:
        cli_version: 0.23.0
        e:
            99acb04n8bo244mus63lmthk9j94o2ec:
                args:
                    - logging.run_name=Bi_SPECTER2_MNRL_AdapterInit_Full
                    - model.name=allenai/specter2_base
                    - model.adapter_name=allenai/specter2
                    - model.freeze_base=false
                    - training.loss_type=mnrl
                    - training.learning_rate=2e-5
                    - data.train_file=data/processed/training_dataset_abstract_cleaned_v3.csv
                codePath: scripts/run_train.py
                codePathLocal: scripts/run_train.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "982820896768"
                        used: "923215896576"
                email: reoreo01.123@gmail.com
                executable: /usr/bin/python
                git:
                    commit: 8243697dbb3f11090f909a65219eece850ef1df2
                    remote: https://github.com/ku6kaw/S2ORCRanker
                gpu: NVIDIA RTX A6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-b6e6e0e3-0979-08d4-7b26-7ebfb7c03ea4
                host: lssgpu
                memory:
                    total: "67242205184"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/kurokawa/Projects/S2ORCRanker/scripts/run_train.py
                python: CPython 3.10.12
                root: /home/kurokawa/Projects/S2ORCRanker
                startedAt: "2025-11-26T21:46:08.254689Z"
                writerId: 99acb04n8bo244mus63lmthk9j94o2ec
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 51
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 51
                - 53
                - 71
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.12
            "5": 0.23.0
            "6": 4.40.0
            "12": 0.23.0
            "13": linux-x86_64
data:
    value:
        format: pair
        num_proc: 4
        train_file: data/processed/training_dataset_abstract_cleaned_v3.csv
        val_size: 0.2
debug:
    value: false
logging:
    value:
        project_name: s2orc-ranker
        run_name: Bi_SPECTER2_MNRL_AdapterInit_Full
        tags: []
        use_wandb: true
model:
    value:
        adapter_name: allenai/specter2
        freeze_base: false
        head_type: ranknet
        max_length: 512
        name: allenai/specter2_base
        type: bi_encoder
seed:
    value: 42
training:
    value:
        batch_size: 32
        epochs: 3
        eval_steps: 50
        head_learning_rate: 2e-05
        learning_rate: 2e-05
        logging_steps: 10
        loss_type: mnrl
        margin: 1
        output_dir: /home/kurokawa/Projects/S2ORCRanker/models/checkpoints/bi_encoder/Bi_SPECTER2_MNRL_AdapterInit_Full
        patience: 3
        save_steps: 50
        save_total_limit: 2
        warmup_ratio: 0.1
        weight_decay: 0.01
